spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: wanide
    password: "000000"

mybatis:
  type-aliases-package: com.lyr.pojo
  mapper-locations: classpath:mapper/*.xml
